# -*- coding: utf-8 -*-
"""Estrack_Training_Simulator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TSIHWCRGhrp72HrgwGAUnSJ2_mFjeoeV
"""

from flask import Flask, render_template, request, redirect, session
import random
import os

app = Flask(__name__)
app.secret_key = "estrack_exam_secret"

PASS_THRESHOLD = 0.8

# ---------------- QUESTION BANK ----------------

questions = [

{
"question":"The correct workstation startup command is:",
"options":[
"ssh -x stc@sce25 startupws.sh",
"ssh -x stc@sce25 > startupws.sh",
"ssh stc@sce25 -x > startupws.sh",
"startupws.sh | ssh -x stc@sce25"
],
"correct":"ssh -x stc@sce25 > startupws.sh",
"explanation":"This is the only correct syntax."
},

{
"question":"During ranging calibration TTCP and DMD alarms occur because:",
"options":[
"Carrier loop instability",
"Uplink carrier without modulation",
"Es/No below threshold",
"Sweep not executed"
],
"correct":"Uplink carrier without modulation",
"explanation":"During ranging calibration the carrier is present without modulation."
},

{
"question":"Interrupting ranging calibration risks:",
"options":[
"Loss of spacecraft lock",
"Leaving subsystems in inconsistent configuration",
"Resetting uplink chain",
"Forcing re-sweep"
],
"correct":"Leaving subsystems in inconsistent configuration",
"explanation":"Stopping the procedure leaves subsystems inconsistent and manual configuration may be required."
},

{
"question":"During pre-pass the carrier is visible but there is no modulation. Most likely:",
"options":[
"Sweep not executed",
"Idle pattern active",
"Ranging calibration ongoing",
"Coherency active"
],
"correct":"Ranging calibration ongoing",
"explanation":"During ranging calibration the signal loops inside TTCP so the antenna radiates carrier but no modulation."
},

{
"question":"Carrier Loop Level (025) most directly reflects:",
"options":[
"Signal-to-noise ratio",
"Received signal power",
"Doppler tracking accuracy",
"Baseband stability"
],
"correct":"Received signal power",
"explanation":"Carrier Loop Level is measured in dBm and measures signal strength."
},

{
"question":"Estimated Es/No (085) measures:",
"options":[
"Carrier frequency offset",
"Signal quality",
"Radiated uplink stability",
"Diversity combining efficiency"
],
"correct":"Signal quality",
"explanation":"Es/No is the signal to noise ratio."
},

{
"question":"Stable AGC with falling Es/No indicates:",
"options":[
"Carrier loss",
"Signal quality degradation",
"SPAN misconfiguration",
"Wrong intermediate frequency"
],
"correct":"Signal quality degradation",
"explanation":"Power remains stable but noise increases."
},

{
"question":"Actual Intermediate Frequency (004) displays:",
"options":[
"Modulated carrier",
"Unmodulated carrier at 230 MHz",
"Doppler shift",
"Ranging tone"
],
"correct":"Unmodulated carrier at 230 MHz",
"explanation":"The IF monitor shows the carrier before modulation."
},

{
"question":"SPAN backend must be configured using:",
"options":[
"ULM radiated frequency",
"DMD average IF frequency",
"Carrier Loop Level",
"Estimated Es/No"
],
"correct":"DMD average IF frequency",
"explanation":"Backend spectrum analyser monitors telemetry from the demodulator."
},

{
"question":"SPAN frontend must be configured using:",
"options":[
"ULM actual radiated frequency",
"DMD IF frequency",
"Carrier Loop Level",
"ADLS input"
],
"correct":"ULM actual radiated frequency",
"explanation":"Frontend monitors uplink radiation."
},

{
"question":"Only one spacecraft visible during MSPA support. First action:",
"options":[
"Change SPAN bandwidth",
"Change ADLS input",
"Check mission schedule and PPCP",
"Enable coherency"
],
"correct":"Check mission schedule and PPCP",
"explanation":"Multiple spacecraft may start transmitting at different times."
},

{
"question":"Correct Kiruna uplink path:",
"options":[
"TCU → IFM1 → AULS → SSPA → Polarizer → Antenna",
"IFM1 → TCU → AULS → SSPA",
"TCU → AULS → IFM1 → SSPA",
"TCU → IFM1 → SSPA → AULS"
],
"correct":"TCU → IFM1 → AULS → SSPA → Polarizer → Antenna",
"explanation":"TCU generates telecommands, IFM1 modulates IF, AULS routes signal, SSPA amplifies, Polarizer prepares radiation."
},

{
"question":"Kiruna S-band downlink path:",
"options":[
"SLNA → SDC → ADLS → CORTEX",
"SLNA → ADLS → SDC → CORTEX",
"SDC → SLNA → ADLS",
"SLNA → CORTEX"
],
"correct":"SLNA → SDC → ADLS → CORTEX",
"explanation":"SLNA amplifies signal, SDC downconverts, ADLS routes signal, CORTEX processes telemetry."
},

{
"question":"X-band support at Kiruna exists:",
"options":[
"For all spacecraft",
"Only when ADLS configured",
"Only for Cryosat",
"When IFR4 active"
],
"correct":"Only for Cryosat",
"explanation":"Cryosat uses the CHRD demodulator chain."
},

{
"question":"IFR2 + IFR3 correspond to:",
"options":[
"RAU",
"TMUA",
"DCU diversity combiner",
"TMUB"
],
"correct":"DCU diversity combiner",
"explanation":"They combine TMUA and TMUB."
},

{
"question":"Baseband swap is justified when:",
"options":[
"Display freeze",
"Prime chain failure",
"Es/No fluctuation",
"Weak SPAN signal"
],
"correct":"Prime chain failure",
"explanation":"Swap restores telecommand capability quickly."
},

{
"question":"Tone ranging operates with:",
"options":[
"GMD only",
"RCD",
"TMUA",
"ADLS"
],
"correct":"RCD",
"explanation":"Tone ranging operates only with Remnant Carrier."
},

{
"question":"Pseudo-noise ranging operates with:",
"options":[
"RCD only",
"GMD only",
"RCD and GMD",
"RAU"
],
"correct":"RCD and GMD",
"explanation":"Pseudo noise works with both carrier types."
},

{
"question":"Sweep is performed to:",
"options":[
"Increase transmit power",
"Improve spacecraft receiver lock",
"Stabilize AGC",
"Calibrate delay"
],
"correct":"Improve spacecraft receiver lock",
"explanation":"Sweep transmits across wider frequency range."
},

{
"question":"Telemetry degrades but carrier remains. First action:",
"options":[
"Re-sweep",
"Increase power",
"Ask mission to repulse DMD",
"Switch to coherent"
],
"correct":"Ask mission to repulse DMD",
"explanation":"Demodulator repulse can restore lock."
},

{
"question":"Re-sweep is more justified when:",
"options":[
"Deep space apogee",
"Supporting polar missions with short EPD",
"During coherency",
"During ranging"
],
"correct":"Supporting polar missions with short EPD",
"explanation":"Polar missions have very short propagation delay."
},

{
"question":"In coherent mode downlink frequency is:",
"options":[
"Generated onboard",
"Derived from uplink signal",
"Controlled by ADLS",
"Set by SPAN"
],
"correct":"Derived from uplink signal",
"explanation":"The spacecraft converts received uplink frequency."
},

{
"question":"Telemetry intermittent and DMD repulse fails. Next action:",
"options":[
"Re-sweep",
"Recalculate downlink frequency",
"Increase power",
"Swap chain"
],
"correct":"Recalculate downlink frequency",
"explanation":"Frequency plan may need recalculation."
},

{
"question":"Radiation inhibited at 8° elevation during deep space support:",
"options":[
"RF Mute Deep Space profile",
"Inhibitor",
"Polarizer fault",
"SSPA disabled"
],
"correct":"RF Mute Deep Space profile",
"explanation":"Deep space RF mute prevents radiation below 10°."
},

{
"question":"What are Service Instances?",
"options":[
"Configuration files for return and forward sessions",
"Backup TTCP configurations",
"Spectrum analyser profiles",
"RF safety configurations"
],
"correct":"Configuration files for return and forward sessions",
"explanation":"They configure spacecraft traffic for return session and forward CLTU session."
}

]

# ---------------- ROUTES ----------------

@app.route("/")
def index():
    return render_template("index.html")


@app.route("/start")
def start():

    session["questions"] = random.sample(questions, len(questions))
    session["index"] = 0
    session["score"] = 0
    session["failed"] = []

    return redirect("/exam")


@app.route("/exam", methods=["GET","POST"])
def exam():

    if request.method == "POST":

        choice = request.form["answer"]
        q = session["questions"][session["index"]]

        if choice == q["correct"]:
            session["score"] += 1
        else:
            failed = session["failed"]
            failed.append({
                "question": q["question"],
                "your": choice,
                "correct": q["correct"],
                "explanation": q["explanation"]
            })
            session["failed"] = failed

        session["index"] += 1

    if session["index"] >= len(session["questions"]):
        return redirect("/result")

    q = session["questions"][session["index"]]

    options = q["options"].copy()
    random.shuffle(options)

    return render_template(
        "exam.html",
        number=session["index"]+1,
        question=q["question"],
        options=options
    )


@app.route("/result")
def result():

    score = session["score"]
    failed = session["failed"]

    passed = score/25 >= PASS_THRESHOLD

    return render_template(
        "result.html",
        score=score,
        passed=passed,
        failed=failed
    )


if __name__ == "__main__":
    app.run(debug=True)